# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PiControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pin_number', models.IntegerField()),
                ('is_thermometer', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manuel', models.BooleanField(default=False)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('range', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('temp_pin_id', models.IntegerField()),
                ('pump_pin_id', models.IntegerField()),
                ('heater_pin_id', models.IntegerField()),
            ],
        ),
    ]
