# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PiControl', '0002_pin_tempcontrol'),
        ('PiControl', '0003_time_bands_changes_to_tempcontro'),
    ]

    operations = [

    ]