# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PiControl', '0004_merge_20170416_1556'),
        ('PiControl', '0005_add_manuel_toggle_off'),
    ]

    operations = [
    ]